/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [MAHD]
      ,[MASP]
      ,[MANV]
      ,[MAKH]
      ,[NGAYLAP]
      ,[SOLUONG]
  FROM [QLShowroom].[dbo].[HOADON]
  --! Thống kê theo ngày
  select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where HOADON.NGAYLAP = '1999-01-01'



  CREATE FUNCTION thongKeNgay (
    @ngay date
)
RETURNS TABLE
AS
RETURN
	 select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where HOADON.NGAYLAP = @ngay

  --!Thống kê theo tháng
    select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where MONTH(HOADON.NGAYLAP) = '1' and YEAR(HOADON.NGAYLAP) = '1999'

  alter FUNCTION thongKeThang (
    @thang INT,
	@nam int
)
RETURNS TABLE
AS
RETURN
	 select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where month(HOADON.NGAYLAP) = @thang and YEAR(HOADON.NGAYLAP) = @nam

  --! thống kê theo năm
	 select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where Year(HOADON.NGAYLAP) = '1999'

CREATE FUNCTION thongKeNam (
    @nam INT
)
RETURNS TABLE
AS
RETURN
	 select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHA
  on HOADON.MANV = NHANVIEN.MANV where Year(HOADON.NGAYLAP) = @namCHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 

select * from thongKeNam(1999)
select * from thongKeNgay('1999-01-01')
select * from thongKeThang(1,1999)



  --! thống kê theo quý

      select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where  YEAR(HOADON.NGAYLAP)='1999' AND NGAYLAP IN (
   select  NGAYLAP     from HOADON  where  MONTH(HOADON.NGAYLAP) BETWEEN 1 AND 3
  )

  CREATE FUNCTION thongKeTheoQuy (
	@quybd int,
	@quykt int,
    @nam INT
)
RETURNS TABLE
AS
RETURN
	
	   select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where  YEAR(HOADON.NGAYLAP)=@nam AND NGAYLAP IN (
   select  NGAYLAP     from HOADON  where  MONTH(HOADON.NGAYLAP) BETWEEN @quybd AND @quykt)


        select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where  YEAR(HOADON.NGAYLAP)='1999' AND NGAYLAP IN (
   select  NGAYLAP     from HOADON  where  MONTH(HOADON.NGAYLAP) BETWEEN 4 AND 6
  )

        select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where  YEAR(HOADON.NGAYLAP)='1999' AND NGAYLAP IN (
   select  NGAYLAP     from HOADON  where  MONTH(HOADON.NGAYLAP) BETWEEN 7 AND 9
  )

        select MAHD,TENSP,TENNV,TENKH, NGAYLAP, HOADON.SOLUONG 
  from HOADON inner join SANPHAM 
  on HOADON.MASP = SANPHAM.MASP inner join KHACHHANG
  on HOADON.MAKH = KHACHHANG.MAKH inner join NHANVIEN 
  on HOADON.MANV = NHANVIEN.MANV where  YEAR(HOADON.NGAYLAP)='1999' AND NGAYLAP IN (
   select  NGAYLAP     from HOADON  where  MONTH(HOADON.NGAYLAP) BETWEEN 10 AND 12
  )




  