/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitaplon.community.com.views;

import baitaplon.community.com.controller.ThongKeController;
import com.toedter.calendar.demo.DateChooserPanel;
import community.com.model.ThongKe;
import java.sql.Date;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.JDatePicker;
import com.toedter.calendar.JDateChooser;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author hoang
 */
public class QLBaoBaoDoanhThu extends javax.swing.JFrame {

    /**
     * Creates new form QLBaoBaoDoanhThu
     */
    public QLBaoBaoDoanhThu() {
        initComponents();
        dateChoose.setEnabled(false);
        cbThang.setEnabled(false);
        cbQuy.setEnabled(false);

        jSpinnerNam.setEnabled(false);
        jSpinnerNamThang.setEnabled(false);
        jSpinnerNamQuy.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdThongKeTheoNgay = new javax.swing.JRadioButton();
        rdQuy = new javax.swing.JRadioButton();
        dateChoose = new com.toedter.calendar.JDateChooser();
        rdThang = new javax.swing.JRadioButton();
        rdNam = new javax.swing.JRadioButton();
        cbQuy = new javax.swing.JComboBox<>();
        cbThang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tongSLDon = new javax.swing.JLabel();
        tongSLKhach = new javax.swing.JLabel();
        tongDoanhThu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSpinnerNamQuy = new javax.swing.JSpinner();
        jSpinnerNam = new javax.swing.JSpinner();
        jSpinnerNamThang = new javax.swing.JSpinner();
        Ngày = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý các báo cáo doanh thu");

        buttonGroup1.add(rdThongKeTheoNgay);
        rdThongKeTheoNgay.setText("Thống kê theo ngày");
        rdThongKeTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdThongKeTheoNgayActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdQuy);
        rdQuy.setText("Thống kê theo quý");
        rdQuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdQuyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdThang);
        rdThang.setText("Thống kê theo tháng");
        rdThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdThangActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNam);
        rdNam.setText("Thống kê theo năm");
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });

        cbQuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        tableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Tên SP", "Tên NV", "Tên KH", "Ngày Lập", "Số Lượng"
            }
        ));
        jScrollPane1.setViewportView(tableThongKe);

        jLabel4.setText("Doanh thu ước tính:");

        tongSLDon.setText("0");

        tongSLKhach.setText("0");

        tongDoanhThu.setText("0");

        jLabel3.setText("Tổng số khách:");

        jLabel2.setText("Số lượng đơn:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        jButton1.setText("Thống Kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JComponent edit1 = new JSpinner.NumberEditor(jSpinnerNamQuy,"#####");
        jSpinnerNamQuy.setEditor(edit1);
        jSpinnerNamQuy.setModel(new javax.swing.SpinnerNumberModel(2020, 1900, 2050, 1));

        JComponent edit12 = new JSpinner.NumberEditor(jSpinnerNam,"#####");
        jSpinnerNam.setEditor(edit12);
        jSpinnerNam.setModel(new javax.swing.SpinnerNumberModel(2020, 1900, 2050, 1));

        JComponent edit3 = new JSpinner.NumberEditor(jSpinnerNamThang,"#####");
        jSpinnerNamThang.setEditor(edit3);
        jSpinnerNamThang.setModel(new javax.swing.SpinnerNumberModel(2020, 1900, 2020, 1));

        Ngày.setName(""); // NOI18N
        Ngày.setText("Ngày");

        label2.setText("Tháng");

        label3.setText("Năm");

        label4.setText("Qúy");

        label5.setText("Năm");

        label6.setText("Năm");

        jButton2.setText("Export (excel)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(rdThongKeTheoNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addComponent(rdQuy, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdNam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ngày, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSpinnerNam, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbThang, 0, 93, Short.MAX_VALUE)
                    .addComponent(cbQuy, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerNamQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jSpinnerNamThang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tongSLKhach)
                            .addComponent(tongSLDon)
                            .addComponent(tongDoanhThu))
                        .addGap(616, 616, 616))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 245, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdThongKeTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ngày, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rdThang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerNamThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(5, 5, 5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerNam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rdQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbQuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerNamQuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tongSLDon)
                        .addGap(18, 18, 18)
                        .addComponent(tongSLKhach)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tongDoanhThu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdThongKeTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdThongKeTheoNgayActionPerformed
        // TODO add your handling code here:'
        {
           
            dateChoose.setEnabled(true);
            cbThang.setEnabled(false);
            cbQuy.setEnabled(false);
            jSpinnerNam.setEnabled(false);
             
        }


    }//GEN-LAST:event_rdThongKeTheoNgayActionPerformed

    private void rdThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdThangActionPerformed
        // TODO add your handling code here:if(rdThang.isSelected())
        {
        
            cbThang.setEnabled(true);
            dateChoose.setEnabled(false);
            cbQuy.setEnabled(false);
            jSpinnerNam.setEnabled(false);
            jSpinnerNamThang.setEnabled(true);
            jSpinnerNamQuy.setEnabled(false);
        }
    }//GEN-LAST:event_rdThangActionPerformed

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        // TODO add your handling code here:spinnerThang.setEnabled(true);
        cbThang.setEnabled(false);
        dateChoose.setEnabled(false);
        cbQuy.setEnabled(false);
        jSpinnerNam.setEnabled(true);
        jSpinnerNamThang.setEnabled(false);
        jSpinnerNamQuy.setEnabled(false);

    }//GEN-LAST:event_rdNamActionPerformed

    private void rdQuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdQuyActionPerformed
        // TODO add your handling code here:
        dateChoose.setEnabled(false);
        cbThang.setEnabled(false);
        cbQuy.setEnabled(true);
        jSpinnerNam.setEnabled(false);
        jSpinnerNamThang.setEnabled(false);
        jSpinnerNamQuy.setEnabled(true);
    }//GEN-LAST:event_rdQuyActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (rdThongKeTheoNgay.isSelected()) {
            if (dateChoose.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong!");
                return;
            }
            hienThi(dateChoose, null, null, null, 1);
            hienThiTongTheoNgay(tongDoanhThu, tongSLKhach, tongDoanhThu);
        }
        if (rdThang.isSelected()) {
           
            hienThi(null, cbThang, jSpinnerNamThang, null, 2);
            hienThiTong(tongDoanhThu, tongSLKhach, tongDoanhThu);

        }
        if (rdNam.isSelected()) {
            hienThi(null, null, jSpinnerNam, null, 3);
            hienThiTongTheoNam(tongDoanhThu, tongSLKhach, tongDoanhThu);
        }
        if (rdQuy.isSelected()) {
            hienThi(null, null, jSpinnerNamQuy, cbQuy, 4);
            hienThiTongTheoQuy(tongDoanhThu, tongSLKhach, tongDoanhThu);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (tableThongKe.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa có dữ liệu export !");
            return;
        }
        FileOutputStream excelFOU = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook excelJTableExporter = null;
        JFileChooser excelFileChooser = new JFileChooser("C:\\Users\\hoang\\OneDrive\\Desktop\\JAVA\\BaiTapLon");
        excelFileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
//            FileOutputStream excelFOU = null;
            try {
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable Sheet");
                XSSFRow excelRow = excelSheet.createRow(0);
                XSSFCell excelCell = excelRow.createCell(0);
                excelCell.setCellValue("Quản lý các báo cáo doanh thu");
                excelSheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 5));
                excelCell = excelRow.createCell(5);

                excelRow = excelSheet.createRow(1);
                excelCell = excelRow.createCell(0);
                excelCell.setCellValue("Mã HD");
                excelCell = excelRow.createCell(1);
                excelCell.setCellValue("Tên SP");
                excelCell = excelRow.createCell(2);
                excelCell.setCellValue("Tên NV");
                excelCell = excelRow.createCell(3);
                excelCell.setCellValue("Tên KH");
                excelCell = excelRow.createCell(4);
                excelCell.setCellValue("Ngày Lập");
                excelCell = excelRow.createCell(5);
                excelCell.setCellValue("Số Lượng");
                for (int i = 0; i < tableThongKe.getRowCount(); i++) {
                    excelRow = excelSheet.createRow(i + 2);
                    for (int j = 0; j < tableThongKe.getColumnCount(); j++) {
                        excelCell = excelRow.createCell(j);
                        excelCell.setCellValue(tableThongKe.getValueAt(i, j).toString());
                    }
                }
                int countTable = tableThongKe.getRowCount();
                excelRow = excelSheet.createRow(countTable + 2);
                excelCell = excelRow.createCell(0);
                excelCell.setCellValue("Số Lượng Đơn");
                excelCell = excelRow.createCell(1);
                excelCell.setCellValue(tongSLDon.getText().toString());

                excelRow = excelSheet.createRow(countTable + 3);
                excelCell = excelRow.createCell(0);
                excelCell.setCellValue("Tổng số khách");
                excelCell = excelRow.createCell(1);
                excelCell.setCellValue(tongSLKhach.getText().toString());

                excelRow = excelSheet.createRow(countTable + 4);
                excelCell = excelRow.createCell(0);
                excelCell.setCellValue("Doanh thu ước tính");
                excelCell = excelRow.createCell(1);
                excelCell.setCellValue(tongDoanhThu.getText().toString());

                excelFOU = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(this, "Export Successfully....!");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelFOU != null) {
                        excelFOU.close();
                    }

                    if (excelJTableExporter != null) {
                        excelJTableExporter.close();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    ThongKeController tk = new ThongKeController();

    public void hienThi(JDateChooser ngay, JComboBox thang, JSpinner nam, JComboBox cbquy, int kieu) {
        DefaultTableModel table = (DefaultTableModel) tableThongKe.getModel();
        table.setRowCount(0);
        Object[] row = new Object[6];
        String date = "";
        int month = 0;
        int year = 0;
        int quy = 0;
        int quybd = 0;
        int quykt = 0;
        switch (kieu) {
            case 1:
                date = new java.sql.Date(ngay.getDate().getTime()).toString();
                break;
            case 2: {
                month = Integer.valueOf(thang.getSelectedItem().toString());
                year = (int) nam.getValue();
                break;
            }

            case 3:
                year = (int) nam.getValue();
                break;
            case 4: {
                quy = Integer.valueOf(cbquy.getSelectedItem().toString());
                year = (int) nam.getValue();
                switch (quy) {
                    case 1: {
                        quybd = 1;
                        quykt = 3;
                        break;
                    }
                    case 2: {
                        quybd = 4;
                        quykt = 6;
                        break;
                    }
                    case 3: {
                        quybd = 7;
                        quykt = 9;
                        break;
                    }
                    case 4: {
                        quybd = 10;
                        quykt = 12;
                        break;
                    }

                }
                break;
            }

        }
        for (ThongKe kh : tk.thongKe(date, month, year, quybd, quykt, kieu)) {
            row[0] = kh.getMaHD();
            row[1] = kh.getTenSP();
            row[2] = kh.getTenNV();
            row[3] = kh.getTenKH();
            row[4] = kh.getNgayLap();
            row[5] = kh.getSoLuong();
            table.addRow(row);

        }

    }

    public void hienThiTong(JLabel tongSL, JLabel tongSLKhach, JLabel tongDoanhThu) {
        tongSLDon.setText(tableThongKe.getRowCount() + "");
        tk.thongKe_TongTien(tongSL, cbThang.getSelectedItem().toString(), jSpinnerNamThang.getValue().toString());
        tk.thongKe_SoKhach(tongSLKhach, cbThang.getSelectedItem().toString(), jSpinnerNamThang.getValue().toString());
    }

    public void hienThiTongTheoNgay(JLabel tongSL, JLabel tongSLKhach, JLabel tongDoanhThu) {
        DateFormat ngay = new SimpleDateFormat("dd");
        DateFormat thang = new SimpleDateFormat("MM");
        DateFormat nam = new SimpleDateFormat("yyyy");

        tongSLDon.setText(tableThongKe.getRowCount() + "");
        tk.thongKe_SoKhachNgay(tongSLKhach, ngay.format(dateChoose.getDate()).toString(), thang.format(dateChoose.getDate()).toString(), nam.format(dateChoose.getDate()).toString());
        tk.tongTienTheoNgay(tongSL, ngay.format(dateChoose.getDate()).toString(), thang.format(dateChoose.getDate()).toString(), nam.format(dateChoose.getDate()).toString());

    }

    public void hienThiTongTheoQuy(JLabel tongSL, JLabel tongSLKhach, JLabel tongDoanhThu) {
        tongSLDon.setText(tableThongKe.getRowCount() + "");
        if (Integer.parseInt(cbQuy.getSelectedItem().toString()) == 1) {
            tk.tongTienTheoQuy(tongSL, "1", "3", jSpinnerNamQuy.getValue().toString());
            tk.thongKe_SoKhachQuy(tongSLKhach, "1", "3", jSpinnerNamQuy.getValue().toString());

        }
        if (Integer.parseInt(cbQuy.getSelectedItem().toString()) == 2) {

            tk.tongTienTheoQuy(tongSL, "4", "6", jSpinnerNamQuy.getValue().toString());
            tk.thongKe_SoKhachQuy(tongSLKhach, "4", "6", jSpinnerNamQuy.getValue().toString());
        }
        if (Integer.parseInt(cbQuy.getSelectedItem().toString()) == 3) {

            tk.tongTienTheoQuy(tongSL, "7", "9", jSpinnerNamQuy.getValue().toString());
            tk.thongKe_SoKhachQuy(tongSLKhach, "7", "9", jSpinnerNamQuy.getValue().toString());
        }
        if (Integer.parseInt(cbQuy.getSelectedItem().toString()) == 4) {

            tk.tongTienTheoQuy(tongSL, "10", "12", jSpinnerNamQuy.getValue().toString());
            tk.thongKe_SoKhachQuy(tongSLKhach, "10", "12", jSpinnerNamQuy.getValue().toString());
        }
    }

    public void hienThiTongTheoNam(JLabel tongSL, JLabel tongSLKhach, JLabel tongDoanhThu) {

        tongSLDon.setText(tableThongKe.getRowCount() + "");
        tk.thongKe_SoKhachNam(tongSLKhach, jSpinnerNam.getValue().toString());
        tk.tongTienTheoNam(tongSL, jSpinnerNam.getValue().toString());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLBaoBaoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLBaoBaoDoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Ngày;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbQuy;
    private javax.swing.JComboBox<String> cbThang;
    private com.toedter.calendar.JDateChooser dateChoose;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerNam;
    private javax.swing.JSpinner jSpinnerNamQuy;
    private javax.swing.JSpinner jSpinnerNamThang;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdQuy;
    private javax.swing.JRadioButton rdThang;
    private javax.swing.JRadioButton rdThongKeTheoNgay;
    private javax.swing.JTable tableThongKe;
    private javax.swing.JLabel tongDoanhThu;
    private javax.swing.JLabel tongSLDon;
    private javax.swing.JLabel tongSLKhach;
    // End of variables declaration//GEN-END:variables
}
