/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitaplon.community.com.views;

import baitaplon.community.com.controller.HoaDonDAO;
import baitaplon.community.com.controller.KhachHangController;
import baitaplon.community.com.controller.NhanVienDAO;
import baitaplon.community.com.controller.SanPhamDAO;
import community.com.model.HoaDon;
import community.com.model.KhachHangObject;
import community.com.model.NhanVien;
import community.com.model.SanPham;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang Trang
 */
public class QLHoaDon extends javax.swing.JFrame {

    private final String[] header = {"STT", "Mã Hóa Đơn", "Mã Nhân Viên", "Mã Khách Hàng", "Ngày Lập", "Tổng tiền"};
    private ArrayList<HoaDon> items = new ArrayList<>();
    private int selectedIndex;
    private DefaultTableModel model;
    DecimalFormat f = new DecimalFormat("#,###,###,###");
    NhanVienDAO nv = new NhanVienDAO();
    ArrayList<NhanVien> dsNV = new ArrayList<NhanVien>();
    KhachHangController kh = new KhachHangController();
    ArrayList<KhachHangObject> dsKH = new ArrayList<KhachHangObject>();
    SanPhamDAO sp = new SanPhamDAO();
    ArrayList<SanPham> dsSP = new ArrayList<SanPham>();

    public QLHoaDon() {

        initComponents();
        dsNV = nv.getNhanViens();
        dsKH = kh.getKH();
        dsSP=sp.getSanPhams();
        for (NhanVien list : dsNV) {
            cbMaNV.addItem(list.getMaNV());
        }

        for (KhachHangObject list : dsKH) {
            cbMAKH.addItem(list.getMaKH());
        }
        for (SanPham list : dsSP) {
            cbMaSP.addItem(list.getMaSP());
        }
        model = (DefaultTableModel) tableHoaDon.getModel();
        model.setColumnIdentifiers(header);
        showTable();
        java.util.Date currentDate = new java.util.Date();
        DateChoose.setDate(currentDate);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void clearText() {
        txtMaHD.setText("");
        cbMAKH.setSelectedIndex(0);
        cbMaNV.setSelectedIndex(0);
        cbMaSP.setSelectedIndex(0);
        txtSoLuong.setText("");
        DateChoose.setDateFormatString("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHoaDon = new javax.swing.JTable();
        DateChoose = new com.toedter.calendar.JDateChooser();
        txtSoLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCTHD = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbMaNV = new javax.swing.JComboBox<>();
        cbMAKH = new javax.swing.JComboBox<>();
        cbMaSP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý hóa đơn bán hàng");
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý hóa đơn bán hàng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableHoaDon);

        DateChoose.setDateFormatString("yyyy-MM-dd");
        DateChoose.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        DateChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateChooseMouseClicked(evt);
            }
        });

        txtSoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoLuongFocusLost(evt);
            }
        });

        jLabel3.setText("Mã hóa đơn");

        jLabel4.setText("Mã KH");

        jLabel5.setText("Ngày lập");

        jLabel7.setText("Mã nhân viên:");

        jLabel6.setText("Số lượng");

        jLabel9.setText("Mã SP");

        txtMaHD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaHDFocusLost(evt);
            }
        });

        jButton1.setText("Xem Chi Tiết HĐ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCTHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCTHD);

        jLabel2.setText("Chi tiết hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHD)
                            .addComponent(DateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(cbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMAKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(cbMaSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(46, 46, 46)
                        .addComponent(btnSua)
                        .addGap(40, 40, 40)
                        .addComponent(btnXoa)
                        .addGap(43, 43, 43)
                        .addComponent(btnTimKiem)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(btnThoat))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DateChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem)
                    .addComponent(btnThoat)
                    .addComponent(jButton1))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        new ScreenMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
      HoaDon item = new HoaDon(txtMaHD.getText(), cbMaNV.getSelectedItem().toString(), cbMaSP.getSelectedItem().toString(),cbMAKH.getSelectedItem().toString(), ((JTextField) DateChoose.getDateEditor().getUiComponent()).getText(), Integer.parseInt(txtSoLuong.getText()));
        if (new HoaDonDAO().updateItem(item)) {
            this.showTable();
            JOptionPane.showMessageDialog(this, "Sửa mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Không sửa được");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // Date ngayLap = java.sql.Date.valueOf(Format1.DATE_FORMAT_SQL.format(DateChoose.getDate()));
       HoaDon item = new HoaDon(txtMaHD.getText());
       int click=JOptionPane.showConfirmDialog(null, "Bạn có chắc chán xóa không");
        if(click==JOptionPane.YES_OPTION)
        {
           try {
               if (new HoaDonDAO().deleteItem(item)) {
                   this.showTable();
                   JOptionPane.showMessageDialog(this, "Xóa thành công!");
                   clearText();
               } else {
                   JOptionPane.showMessageDialog(this, "Không sửa được");
               }  } catch (SQLException ex) {
               Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maHD = txtMaHD.getText().trim();
        items = new HoaDonDAO().searchItem(maHD);

        model.setRowCount(0);
        for (HoaDon item : items) {
            model.addRow(new Object[]{
                model.getRowCount() + 1, item.getMaHD(), item.getMaNV(), item.getMaKH(), item.getNgayLap(), f.format(item.getTongTien())
            });
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tableHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHoaDonMouseClicked

        int row = tableHoaDon.getSelectedRow();
        txtMaHD.setText(model.getValueAt(row, 1).toString());
        cbMaNV.setSelectedItem(model.getValueAt(row, 2).toString());
        cbMAKH.setSelectedItem(model.getValueAt(row, 3).toString());
        
        ((JTextField) DateChoose.getDateEditor().getUiComponent()).setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableHoaDonMouseClicked

    private void DateChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateChooseMouseClicked

    }//GEN-LAST:event_DateChooseMouseClicked

    private void txtSoLuongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoLuongFocusLost

    }//GEN-LAST:event_txtSoLuongFocusLost

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if ("".equals(txtMaHD.getText())) 
            JOptionPane.showMessageDialog(this, "không để trống mã hóa đơn");  
        else if ("".equals(txtSoLuong.getText()))
            JOptionPane.showMessageDialog(this, "không để trống số lượng sản phẩm");  
        else {
            boolean isSuccess = true;

            String maHD = txtMaHD.getText();
            String maNV = cbMaNV.getSelectedItem().toString();
            String maSP = cbMaSP.getSelectedItem().toString();
            String maKH = cbMAKH.getSelectedItem().toString();
            String ngayLap = ((JTextField) DateChoose.getDateEditor().getUiComponent()).getText();
            int soLuong = Integer.parseInt(txtSoLuong.getText());

            if (isSuccess) {
                HoaDon item = new HoaDon(maHD, maNV, maSP, maKH, ngayLap, soLuong);
                if (new HoaDonDAO().addItem(item)) {
                    this.showTable();
                    JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                    clearText();
                } else {
                    JOptionPane.showMessageDialog(this, "Hóa đơn đã tồn tại!");
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            getChiTietHoaDOns();
        } catch (SQLException ex) {
            Logger.getLogger(QLHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCTHDMouseClicked
        model = (DefaultTableModel) tableCTHD.getModel();
        int row = tableCTHD.getSelectedRow();
        cbMaSP.setSelectedItem(model.getValueAt(row, 1).toString());
        txtSoLuong.setText(this.model.getValueAt(row, 2).toString());


    }//GEN-LAST:event_tableCTHDMouseClicked

    private void txtMaHDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaHDFocusLost

    }//GEN-LAST:event_txtMaHDFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHoaDon().setVisible(true);
            }
        });
    }

    public void showTable() {
        items = new HoaDonDAO().getHoaDOns();
        model.setRowCount(0);
        for (HoaDon item : items) {
            model.addRow(new Object[]{
                model.getRowCount() + 1, item.getMaHD(), item.getMaNV(), item.getMaKH(), item.getNgayLap(), f.format(item.getTongTien())
            });
        }
    }

    public void getChiTietHoaDOns() throws SQLException {

        Connection conn = null;
        Statement st = null;

        String url = "jdbc:sqlserver://localhost:1433;databaseName=QLShowroom";
        String user = "sa";
        String pass = "123";

        conn = (Connection) DriverManager.getConnection(url, user, pass);
        st = (Statement) conn.createStatement();
        String sql = "select SANPHAM.MASP,TENSP,HOADON.SOLUONG,SANPHAM.GIA from HOADON INNER JOIN SANPHAM ON HOADON.MASP=SANPHAM.MASP where MAHD='"+ txtMaHD.getText() + "'";
        ResultSet rs = st.executeQuery(sql);
        String[] ar = {"Mã sản phẩm", "tên sản phẩm", "Số lượng", "đơn giá"};
        DefaultTableModel model1 = new DefaultTableModel(ar, 0);
        while (rs.next()) {
            Vector vec = new Vector();
            vec.add(rs.getString("MASP"));
            vec.add(rs.getString("TENSP").trim());
            vec.add(rs.getInt("SOLUONG"));
            vec.add(rs.getDouble("GIA"));
            model1.addRow(vec);
        }
        tableCTHD.setModel(model1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChoose;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbMAKH;
    private javax.swing.JComboBox<String> cbMaNV;
    private javax.swing.JComboBox<String> cbMaSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCTHD;
    private javax.swing.JTable tableHoaDon;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
