/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitaplon.community.com.views;

import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import baitaplon.community.com.controller.SanPhamDAO;
import community.com.model.SanPham;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import validator.Validator;

/**
 *
 * @author Hoang Trang
 */
public class QLSanPham extends javax.swing.JFrame {

    private final String[] header = {"STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Giá", "Kiểu dáng", "Màu Sắc", "Xuất xứ", "Số lượng", "Mô tả"};
    private ArrayList<SanPham> items = new ArrayList<>();
    private int selectedIndex;
    private DefaultTableModel model;
    DecimalFormat f=new DecimalFormat("##,###,###");

    public QLSanPham() {
        initComponents();
        model = (DefaultTableModel) tableQLSanPham.getModel();
        model.setColumnIdentifiers(header);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_TimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableQLSanPham = new javax.swing.JTable();
        txtKieuDang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtxMauSac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sản phẩm");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý sản phẩm");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tableQLSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableQLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQLSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableQLSanPham);

        txtKieuDang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKieuDangFocusLost(evt);
            }
        });

        jLabel2.setText("Mã sản phầm:");

        txtXuatXu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtXuatXuFocusLost(evt);
            }
        });

        jLabel3.setText("Tên sản phẩm");

        jLabel4.setText("Giá");

        jLabel5.setText("Kiểu dáng");

        jLabel6.setText("Màu sắc:");

        jLabel7.setText("Xuất xứ:");

        jLabel8.setText("Mô tả");

        txtMaSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSPFocusLost(evt);
            }
        });
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtMoTa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMoTaFocusLost(evt);
            }
        });

        txtTenSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenSPFocusLost(evt);
            }
        });

        txtGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGiaFocusLost(evt);
            }
        });

        txtxMauSac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtxMauSacFocusLost(evt);
            }
        });

        jLabel9.setText("Số lượng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_them)
                .addGap(41, 41, 41)
                .addComponent(btn_sua)
                .addGap(18, 18, 18)
                .addComponent(btn_xoa)
                .addGap(36, 36, 36)
                .addComponent(btn_TimKiem)
                .addGap(29, 29, 29)
                .addComponent(btnThoat)
                .addGap(100, 138, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKieuDang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSoLuong))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtMoTa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtxMauSac)
                                            .addComponent(txtXuatXu)))))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtxMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKieuDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_sua)
                        .addComponent(btn_TimKiem)
                        .addComponent(btn_xoa)
                        .addComponent(btnThoat))
                    .addComponent(btn_them))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void clearText() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtGia.setText("");
        txtKieuDang.setText("");
        txtxMauSac.setText("");
        txtXuatXu.setText("");
        txtSoLuong.setText("");
        txtMoTa.setText("");
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        if("".equals(txtMaSP.getText())) JOptionPane.showMessageDialog(this, "không để trống mã sản phẩm");
        else if("".equals(txtTenSP.getText())) JOptionPane.showMessageDialog(this, "không để trống tên sản phẩm");
        else if("".equals(txtGia.getText())) JOptionPane.showMessageDialog(this, "không để trống giá tiền");
        else if("".equals(txtKieuDang.getText())) JOptionPane.showMessageDialog(this, "không để trống kiểu dáng");
        else if("".equals(txtxMauSac.getText())) JOptionPane.showMessageDialog(this, "không để trống màu sắc");
        else if("".equals(txtXuatXu.getText())) JOptionPane.showMessageDialog(this, "không để trống xuất xứ");
        else if("".equals(txtSoLuong.getText())) JOptionPane.showMessageDialog(this, "không để trống số lượng");
        else if("".equals(txtMoTa.getText())) JOptionPane.showMessageDialog(this, "không để trống mô tả");
        else{
        boolean isSuccess = true;
        String maSP = txtMaSP.getText();
        String tenSP = txtTenSP.getText();
        Double gia =Double.parseDouble( txtGia.getText());
        String kieuDang = txtKieuDang.getText();
        String mauSac = txtxMauSac.getText();
        String xuatXu = txtXuatXu.getText();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        String moTa = txtMoTa.getText();

        if (isSuccess) {
            SanPham item = new SanPham(maSP, tenSP,gia, kieuDang, mauSac, xuatXu,soLuong, moTa);
            if (new SanPhamDAO().addItem(item)) {
                this.showTable();
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                clearText();
            } else {
                JOptionPane.showMessageDialog(this, "Sản Phẩm đã tồn tại!");
            }
        }}

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        SanPham item = new SanPham(txtMaSP.getText(), txtTenSP.getText(), Double.parseDouble(txtGia.getText()), txtKieuDang.getText(), txtxMauSac.getText(), txtXuatXu.getText(), Integer.parseInt(txtSoLuong.getText()), txtMoTa.getText());
        if (new SanPhamDAO().updateItem(item)) {
            this.showTable();
            JOptionPane.showMessageDialog(this, "Sửa mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Không sửa được");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
       SanPham item = new SanPham(txtMaSP.getText());
        int click=JOptionPane.showConfirmDialog(null, "Bạn có chắc chán xóa không");
        if(click==JOptionPane.YES_OPTION)
        {
        if (new SanPhamDAO().deleteItem(item)) {
            this.showTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            clearText();
        } else {
            JOptionPane.showMessageDialog(this, "Không sửa được");
        }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        String maSP = txtMaSP.getText().trim();
        String tenSP = txtTenSP.getText().trim();
        items = new SanPhamDAO().searchItem(maSP,tenSP);
        model.setRowCount(0);
        for (SanPham item : items) {
            model.addRow(new Object[]{
                model.getRowCount() + 1, item.getMaSP(), item.getTenSP(), f.format(item.getGia()), item.getKieuDang(), item.getMauSac(), item.getXuatXu(), item.getMoTa()
            });
        }
        clearText();

    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        new ScreenMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtKieuDangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKieuDangFocusLost

    }//GEN-LAST:event_txtKieuDangFocusLost

    private void txtXuatXuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXuatXuFocusLost

    }//GEN-LAST:event_txtXuatXuFocusLost

    private void txtMaSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSPFocusLost

    }//GEN-LAST:event_txtMaSPFocusLost

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtMoTaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMoTaFocusLost

    }//GEN-LAST:event_txtMoTaFocusLost

    private void txtTenSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenSPFocusLost

    }//GEN-LAST:event_txtTenSPFocusLost

    private void txtGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaFocusLost

    }//GEN-LAST:event_txtGiaFocusLost

    private void txtxMauSacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtxMauSacFocusLost

    }//GEN-LAST:event_txtxMauSacFocusLost

    private void tableQLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQLSanPhamMouseClicked
        int row = tableQLSanPham.getSelectedRow();
        txtMaSP.setText(model.getValueAt(row, 1).toString());
        txtTenSP.setText(model.getValueAt(row, 2).toString());
        txtGia.setText(model.getValueAt(row, 3).toString());
        txtKieuDang.setText(model.getValueAt(row, 4).toString());
        txtxMauSac.setText(model.getValueAt(row, 5).toString());
        txtXuatXu.setText(model.getValueAt(row, 6).toString());
        txtSoLuong.setText(model.getValueAt(row, 7).toString());
        txtMoTa.setText(model.getValueAt(row, 8).toString());
    }//GEN-LAST:event_tableQLSanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSanPham().setVisible(true);

            }
        });
    }

    public void showTable() {
        items = new SanPhamDAO().getSanPhams();
        model.setRowCount(0);
        for (SanPham item : items) {
            model.addRow(new Object[]{
                model.getRowCount() + 1, item.getMaSP(), item.getTenSP(), f.format(item.getGia()), item.getKieuDang(), item.getMauSac(), item.getXuatXu(), item.getSoLuong(), item.getMoTa()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableQLSanPham;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtKieuDang;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtXuatXu;
    private javax.swing.JTextField txtxMauSac;
    // End of variables declaration//GEN-END:variables
}
